# 1- Fondamentaux du Python

## a) Dictionnaires et tuples

### Créez un tuple qui associe votre login à votre âge

In [1]:
("fbabin", 25)

('fbabin', 25)

### Initialisez un dictionnaire à deux entrées qui associe le login de chacun de vos voisins à leur âge

In [4]:
dict = {"pdespres": 46, "pchoffe": 56}
dict

{'pchoffe': 56, 'pdespres': 46}

### Récupérez l'âge de l'un d'entre eux à partir du dictionnaire

In [5]:
dict["pdespres"]

46

### Ajoutez une entrée avec votre propre login

In [6]:
dict["fbabin"]=25

## b) Manipulation de listes

### Créez une liste A contenant les entiers suivants: 1, 3, 2, 7, 4, 10, 46

In [9]:
A = [1,3,2,7,4,10,46]


### Affichez les 3 premiers éléments de la liste A - en une ligne de code

In [10]:
A[:3]

[1, 3, 2]

### Créez une liste B qui contient seulement les 3e, 4e et 5e éléments de A . Votre ligne de code ne devrait contenir que 8 caractères (sans compter les espaces) - Vérifiez bien votre résultat!

In [24]:
B = A[3:6]
B

[7, 4, 10]

### Concaténez les listes A et B pour former la liste C

In [13]:
C = A + B

### Ajoutez le nombre 5 à la liste A

In [14]:
C.append(5)

### Ajoutez un élément nul à la liste C

In [15]:
C.append(None)

## b) Fonctions

### Écrivez une fonction qui prend comme arguments une liste 'lst' et un entier 'n' et retourne le résultat de n concaténations de 'lst' avec elle-même (ex: lst=[1,2,3], n=2 --> [1,2,3,1,2,3])

In [25]:
def nconcat(lst, n):
    new = []
    while n != 0:
        new += lst
        n -= 1
    return new

result = nconcat(B, 2)
result

[7, 4, 10, 7, 4, 10]

### Vous voulez rendre le paramètre 'n' optionnel et fixer sa valeur à 2 par défaut. Comment faites-vous?

In [28]:
def nconcat(lst, n=2):
    new = []
    while n != 0:
        new += lst
        n -= 1
    return new

result = nconcat(B)
result

[7, 4, 10, 7, 4, 10]

## c) Boucles

### Avec une boucle 'while', imprimez chaque élément de la liste C jusqu'à l'élément nul

In [30]:
i = 0
while C[i] != None:
    print(str(C[i]))
    i += 1

1
3
2
7
4
10
46
7
4
10
5


### Calculez, avec une boucle 'for', le nombre d'entiers pairs présents dans la liste A

In [32]:
n = 0
for elem in A:
    if (elem % 2 == 0):
        n += 1
print (str(n))

4


### Réécrivez l'expression suivante avec une boucle 'for' sur plusieurs lignes

In [ ]:
C = [element for element in A if element %2 == 0]

In [35]:
C = []
for elem in A:
    if (elem % 2 == 0):
        C.append(elem)
print (C)

[2, 4, 10, 46]


# 2- Opérations sur matrices avec numpy

### Transformer les listes A et B en tableaux numpy a et b

In [37]:
import numpy as np

a = np.asarray(A)
b = np.asarray(B)

### Concaténez-les pour former un tableau c (a, b --> c)

In [41]:
c = np.concatenate((a, b), axis=0)
c

array([ 1,  3,  2,  7,  4, 10, 46,  7,  4, 10])

### Divisez tous les éléments de c par 3 (sans utiliser de boucle)

In [40]:
c / 3

array([ 0.33333333,  1.        ,  0.66666667,  2.33333333,  1.33333333,
        3.33333333, 15.33333333,  2.33333333,  1.33333333,  3.33333333])

### Calculez la somme de tous les éléments de c (sans utiliser de boucle)

In [42]:
np.sum(c)

94

### Exécutez les trois cellules suivantes pour visualiser les matrices M et N

In [43]:
M = np.random.randint(10, size=(4,4))
N = np.random.randint(10, size=(4,4))

In [44]:
M

array([[1, 8, 3, 6],
       [4, 2, 5, 3],
       [9, 6, 1, 4],
       [2, 2, 9, 4]])

In [45]:
N

array([[7, 6, 7, 1],
       [3, 7, 4, 5],
       [7, 2, 2, 9],
       [8, 1, 8, 0]])

### Aditionnez les deux matrices

In [47]:
np.add(N, M)

array([[ 8, 14, 10,  7],
       [ 7,  9,  9,  8],
       [16,  8,  3, 13],
       [10,  3, 17,  4]])

### Calculez le produit matriciel de M et N. Vérifiez votre opération en calculant les premières cellules à la main

In [48]:
np.dot(N, M)

array([[ 96, 112,  67,  92],
       [ 77,  72,  93,  75],
       [ 51,  90, 114,  92],
       [ 84, 114,  37,  83]])

### ** Bonus: Écrivez vous-mêmes une fonction de produit matriciel, avec des boucles imbriquées 